name: Build Arduino ESP32

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI manually
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install ESP32 board
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 --output-dir build src

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: build/*.bin