name: Build ESP32 Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Cấu hình Board ESP32
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Biên dịch code
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 ./ --output-dir build

      - name: Lưu file .bin
        uses: actions/upload-artifact@v3
        with:
          name: firmware-bin
          path: build/*.bin